export * from './annotation-adapter';
export * from './epub-loader';
export * from './locator';
export { normalizeText, findBestChapterMatch, shouldShowDriftWarning } from './reanchor';
export type { ReanchorResult, AnnotationAnchor } from './reanchor';
export { reanchorByText, tryReanchor, terminateWorker } from './reanchor-worker';
export * from './toc';
export * from './epub-types';
export * from './sanitizer';
export * from './epub-accessibility';
export * from './fixed-layout';
