#!/usr/bin/env python3
"""
Generate AVAILABLE_SKILLS.md from .agents/skills/ directory.

This script scans the skills directory and creates a markdown file
listing all available skills with their descriptions.
"""

import os
import sys
from pathlib import Path
from typing import Optional

# Configuration
SKILLS_DIR = Path(".agents/skills")
OUTPUT_FILE = Path("agents-docs/AVAILABLE_SKILLS.md")
TEMPLATE = """# Available Skills

Auto-generated from skill definitions. Run this script to regenerate.

| Skill | Description |
|-------|-------------|
{skills_table}

---

*Generated by ./scripts/generate-available-skills.py*
"""


def get_skill_description(skill_path: Path) -> Optional[str]:
    """Extract description from SKILL.md frontmatter."""
    skill_file = skill_path / "SKILL.md"
    if not skill_file.exists():
        return None

    try:
        content = skill_file.read_text(encoding="utf-8")

        # Check for YAML frontmatter
        if content.startswith("---"):
            end_marker = content.find("---", 3)
            if end_marker != -1:
                frontmatter = content[3:end_marker].strip()

                # Extract description
                for line in frontmatter.split("\n"):
                    if line.startswith("description:"):
                        # Handle multi-line descriptions
                        desc = line.split(":", 1)[1].strip()
                        # Remove > and quotes if present
                        desc = desc.strip(">").strip('"').strip("'")
                        return desc

        # Fallback: first line after title
        lines = content.split("\n")
        in_frontmatter = False
        for i, line in enumerate(lines):
            if line.strip() == "---":
                if not in_frontmatter:
                    in_frontmatter = True
                else:
                    in_frontmatter = False
            elif not in_frontmatter and line.startswith("# "):
                # Skip the title, get next non-empty line
                for next_line in lines[i+1:]:
                    if next_line.strip() and not next_line.startswith("#"):
                        return next_line.strip()[:100]  # Limit length
                        break

    except Exception as e:
        print(f"Warning: Could not parse {skill_file}: {e}")

    return None


def get_skill_category(skill_path: Path) -> Optional[str]:
    """Extract category from SKILL.md frontmatter."""
    skill_file = skill_path / "SKILL.md"
    if not skill_file.exists():
        return None

    try:
        content = skill_file.read_text(encoding="utf-8")

        if content.startswith("---"):
            end_marker = content.find("---", 3)
            if end_marker != -1:
                frontmatter = content[3:end_marker].strip()

                for line in frontmatter.split("\n"):
                    if line.startswith("category:"):
                        return line.split(":", 1)[1].strip()

    except Exception:
        pass

    return "general"


def get_all_skills() -> list[tuple[str, str, str]]:
    """Get all skills with their names, descriptions, and categories."""
    skills = []

    if not SKILLS_DIR.exists():
        print(f"Error: Skills directory not found: {SKILLS_DIR}")
        sys.exit(1)

    for item in sorted(SKILLS_DIR.iterdir()):
        if item.is_dir() and not item.name.startswith("."):
            description = get_skill_description(item) or "No description"
            category = get_skill_category(item)
            skills.append((item.name, description, category))

    return skills


def format_skills_table(skills: list[tuple[str, str, str]]) -> str:
    """Format skills into a markdown table."""
    lines = []

    # Group by category
    by_category: dict[str, list[tuple[str, str]]] = {}
    for name, desc, category in skills:
        if category not in by_category:
            by_category[category] = []
        by_category[category].append((name, desc))

    # Format by category
    for category in sorted(by_category.keys()):
        lines.append(f"### {category.title()}")
        lines.append("")
        for name, desc in by_category[category]:
            # Escape pipes in description
            desc_escaped = desc.replace("|", "\\|")
            lines.append(f"| `{name}` | {desc_escaped} |")
        lines.append("")

    return "\n".join(lines)


def main():
    """Main entry point."""
    print(f"Scanning skills in {SKILLS_DIR}...")

    skills = get_all_skills()
    print(f"Found {len(skills)} skills")

    # Create output directory if needed
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    # Generate content
    table = format_skills_table(skills)
    content = TEMPLATE.format(skills_table=table)

    # Write output
    OUTPUT_FILE.write_text(content, encoding="utf-8")
    print(f"Generated {OUTPUT_FILE}")

    # Print summary
    categories: dict[str, int] = {}
    for _, _, cat in skills:
        categories[cat] = categories.get(cat, 0) + 1

    print("\nSkills by category:")
    for cat, count in sorted(categories.items()):
        print(f"  {cat}: {count}")


if __name__ == "__main__":
    main()
