#!/usr/bin/env python3
"""
Generate AVAILABLE_SKILLS.md from .agents/skills/ directory.

This script scans the skills directory and creates a markdown file
listing all available skills with their descriptions.
"""

import os
import sys
from pathlib import Path
from typing import Optional

try:
    import yaml  # type: ignore[import-not-found]
    _HAS_YAML = True
except ImportError:  # pragma: no cover - PyYAML is available in this repo's env
    _HAS_YAML = False

# Configuration
SKILLS_DIR = Path(".agents/skills")
OUTPUT_FILE = Path("agents-docs/AVAILABLE_SKILLS.md")
TEMPLATE = """# Available Skills

Auto-generated from skill definitions. Run this script to regenerate.

| Skill | Description |
|-------|-------------|

{skills_table}

---

*Generated by ./scripts/generate-available-skills.py*
"""


def _extract_frontmatter(content: str) -> Optional[dict]:
    """Parse YAML frontmatter (between leading ``---`` fences) into a dict.

    Uses PyYAML when available so block scalars (``description: >`` / ``|``)
    and quoted values parse correctly. Falls back to a small stdlib parser
    covering the shapes used by SKILL.md files when PyYAML is absent.
    """
    if not content.startswith("---"):
        return None
    end_marker = content.find("\n---", 3)
    if end_marker == -1:
        return None
    frontmatter = content[3:end_marker]

    if _HAS_YAML:
        try:
            data = yaml.safe_load(frontmatter)
            if isinstance(data, dict):
                return data
        except yaml.YAMLError:
            pass  # fall through to stdlib parser

    # Stdlib fallback.
    result: dict = {}
    lines = frontmatter.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            i += 1
            continue
        if ":" not in line:
            i += 1
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        if value in (">", "|"):
            # Folded/literal block scalar: gather indented continuation lines.
            body: list[str] = []
            i += 1
            while i < len(lines) and (lines[i].startswith((" ", "\t"))):
                if lines[i].strip():
                    body.append(lines[i].strip())
                i += 1
            result[key] = " ".join(body)
        elif value and value[0] in ('"', "'"):
            # Quoted scalar (single-line; good enough for fallback).
            quote = value[0]
            inner = value[1:]
            if quote in inner:
                result[key] = inner.split(quote, 1)[0].strip()
            else:
                result[key] = inner.strip()
            i += 1
        else:
            result[key] = value
            i += 1
    return result


def get_skill_description(skill_path: Path) -> Optional[str]:
    """Extract description from SKILL.md frontmatter."""
    skill_file = skill_path / "SKILL.md"
    if not skill_file.exists():
        return None

    try:
        content = skill_file.read_text(encoding="utf-8")
        frontmatter = _extract_frontmatter(content)
        if frontmatter is not None:
            desc = frontmatter.get("description")
            if isinstance(desc, str) and desc.strip():
                return desc.strip()

        # Fallback: first non-empty prose line after the H1 title.
        lines = content.split("\n")
        in_frontmatter = False
        for i, line in enumerate(lines):
            if line.strip() == "---":
                in_frontmatter = not in_frontmatter
                continue
            if in_frontmatter:
                continue
            if line.startswith("# "):
                for next_line in lines[i + 1:]:
                    if next_line.strip() and not next_line.startswith("#"):
                        return next_line.strip()[:100]
                    break
                break
    except Exception as e:
        print(f"Warning: Could not parse {skill_file}: {e}")

    return None


def get_skill_category(skill_path: Path) -> Optional[str]:
    """Extract category from SKILL.md frontmatter."""
    skill_file = skill_path / "SKILL.md"
    if not skill_file.exists():
        return None

    try:
        content = skill_file.read_text(encoding="utf-8")
        frontmatter = _extract_frontmatter(content)
        if frontmatter is not None:
            cat = frontmatter.get("category")
            if isinstance(cat, str) and cat.strip():
                return cat.strip()
    except Exception:
        pass

    return "general"


def get_all_skills() -> list[tuple[str, str, str]]:
    """Get all skills with their names, descriptions, and categories."""
    skills = []

    if not SKILLS_DIR.exists():
        print(f"Error: Skills directory not found: {SKILLS_DIR}")
        sys.exit(1)

    for item in sorted(SKILLS_DIR.iterdir()):
        if item.is_dir() and not item.name.startswith("."):
            description = get_skill_description(item) or "No description"
            category = get_skill_category(item)
            skills.append((item.name, description, category))

    # Return list of unique skill tuples
    return sorted(list(set(skills)))


def format_skills_table(skills: list[tuple[str, str, str]]) -> str:
    """Format skills into a markdown table."""
    lines = []

    # Group by category
    by_category: dict[str, list[tuple[str, str]]] = {}
    for name, desc, category in skills:
        if category not in by_category:
            by_category[category] = []
        by_category[category].append((name, desc))

    # Sort categories and skills within categories
    for category in sorted(by_category.keys()):
        lines.append(f"## {category.title()}")
        lines.append("")
        for name, desc in sorted(by_category[category]):
            # Escape pipes in description
            desc_escaped = desc.replace("|", r"\|")
            lines.append(f"| `{name}` | {desc_escaped} |")
        # Trailing blank line between categories; no blank after the last
        # because the template adds one before the closing `---`.
        lines.append("")

    return "\n".join(lines).rstrip("\n")


def main():
    """Main entry point."""
    print(f"Scanning skills in {SKILLS_DIR}...")

    skills = get_all_skills()
    print(f"Found {len(skills)} skills")

    # Create output directory if needed
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    # Generate content
    table = format_skills_table(skills)
    content = TEMPLATE.format(skills_table=table)

    # Write output
    OUTPUT_FILE.write_text(content, encoding="utf-8")
    print(f"Generated {OUTPUT_FILE}")

    # Print summary
    categories: dict[str, int] = {}
    for _, _, cat in skills:
        categories[cat] = categories.get(cat, 0) + 1

    print("\nSkills by category:")
    for cat, count in sorted(categories.items()):
        print(f"  {cat}: {count}")


if __name__ == "__main__":
    main()
